### ISSUE TITLE
Tracking Eslint 9 compatibility

### ISSUE THREAD

**Issue by chohner** [digitalservicebund/a2j-rechtsantragstelle#781]
Inspired by https://github.com/eslint/eslint/issues/18391

| Dependency| v9 support |
|:-:|:-:|
| [eslint-plugin-import](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks) | ✅ https://github.com/import-js/eslint-plugin-import/issues/2948  | 
| [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) | ✅  https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/978 |
| [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react) | ✅ https://github.com/jsx-eslint/eslint-plugin-react/issues/3699 | 
| [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks) | ✅ https://github.com/facebook/react/issues/28313 | 
| [eslint-plugin-storybook](https://github.com/storybookjs/eslint-plugin-storybook/blob/main/package.json) | ✅ https://github.com/storybookjs/eslint-plugin-storybook/pull/156 | 
| [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/package.json) | ✅ |
| [eslint-plugin-vitest](https://github.com/vitest-dev/eslint-plugin-vitest) | ✅ |

**Comment by pgurusinga** [comment]
@chohner I think Remix removed `eslint-config` as their dependency. Please refer to:
https://github.com/remix-run/remix/issues/7056
https://github.com/remix-run/remix/pull/7597/files

and removal from the template: https://github.com/remix-run/indie-stack/pull/261/files

**Comment by andreasphil** [comment]
@chohner `eslint-plugin-import` is now ESLint v9 compatible, I just upgraded successfully: https://github.com/digitalservicebund/ris-norms/pull/666

**Comment by chohner** [comment]
Nice, I think all the plugins are now supported. thanks for the heads-up

**Comment by chohner** [comment]
Closing since all plugins are eslint 9 compatible now
